# apiVersion: v1
# kind: Namespace
# metadata:
#   name: system
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-switchercanary-manager
  namespace: system
  labels:
    control-plane: bg-switchercanary-manager
spec:
  selector:
    matchLabels:
      control-plane: bg-switchercanary-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: bg-switchercanary-manager
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - command:
            - /usr/bin/bg-switchercanary
          image: ghcr.io/sabaniki/seccamp/bg-switchercanary:latest
          imagePullPolicy: IfNotPresent
          name: manager
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10