apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-switcher-controller-manager
  namespace: system
  labels:
    control-plane: bg-switcher-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: bg-switcher-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: bg-switcher-controller-manager
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - command:
            - /usr/bin/bg-switcher-controller
          image: ghcr.io/sabaniki/seccamp/bg-switcher-controller:latest
          imagePullPolicy: IfNotPresent
          name: manager
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10