//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BbRouterStatus) DeepCopyInto(out *BbRouterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BbRouterStatus.
func (in *BbRouterStatus) DeepCopy() *BbRouterStatus {
	if in == nil {
		return nil
	}
	out := new(BbRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcher) DeepCopyInto(out *BgSwitcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcher.
func (in *BgSwitcher) DeepCopy() *BgSwitcher {
	if in == nil {
		return nil
	}
	out := new(BgSwitcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BgSwitcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherCanary) DeepCopyInto(out *BgSwitcherCanary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherCanary.
func (in *BgSwitcherCanary) DeepCopy() *BgSwitcherCanary {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherCanary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BgSwitcherCanary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherCanaryList) DeepCopyInto(out *BgSwitcherCanaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BgSwitcherCanary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherCanaryList.
func (in *BgSwitcherCanaryList) DeepCopy() *BgSwitcherCanaryList {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherCanaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BgSwitcherCanaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherCanarySpec) DeepCopyInto(out *BgSwitcherCanarySpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]ColorGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherCanarySpec.
func (in *BgSwitcherCanarySpec) DeepCopy() *BgSwitcherCanarySpec {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherCanarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherCanaryStatus) DeepCopyInto(out *BgSwitcherCanaryStatus) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextTimestamp.DeepCopyInto(&out.NextTimestamp)
	in.LastTimestamp.DeepCopyInto(&out.LastTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherCanaryStatus.
func (in *BgSwitcherCanaryStatus) DeepCopy() *BgSwitcherCanaryStatus {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherCanaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherGroup) DeepCopyInto(out *BgSwitcherGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherGroup.
func (in *BgSwitcherGroup) DeepCopy() *BgSwitcherGroup {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BgSwitcherGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherGroupList) DeepCopyInto(out *BgSwitcherGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BgSwitcherGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherGroupList.
func (in *BgSwitcherGroupList) DeepCopy() *BgSwitcherGroupList {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BgSwitcherGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherGroupSpec) DeepCopyInto(out *BgSwitcherGroupSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherGroupSpec.
func (in *BgSwitcherGroupSpec) DeepCopy() *BgSwitcherGroupSpec {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherGroupStatus) DeepCopyInto(out *BgSwitcherGroupStatus) {
	*out = *in
	if in.BbRouters != nil {
		in, out := &in.BbRouters, &out.BbRouters
		*out = make([]BbRouterStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherGroupStatus.
func (in *BgSwitcherGroupStatus) DeepCopy() *BgSwitcherGroupStatus {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherList) DeepCopyInto(out *BgSwitcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BgSwitcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherList.
func (in *BgSwitcherList) DeepCopy() *BgSwitcherList {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BgSwitcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherSpec) DeepCopyInto(out *BgSwitcherSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherSpec.
func (in *BgSwitcherSpec) DeepCopy() *BgSwitcherSpec {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BgSwitcherStatus) DeepCopyInto(out *BgSwitcherStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BgSwitcherStatus.
func (in *BgSwitcherStatus) DeepCopy() *BgSwitcherStatus {
	if in == nil {
		return nil
	}
	out := new(BgSwitcherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColorGroup) DeepCopyInto(out *ColorGroup) {
	*out = *in
	if in.BbRouterNames != nil {
		in, out := &in.BbRouterNames, &out.BbRouterNames
		*out = make([]BbRouterSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColorGroup.
func (in *ColorGroup) DeepCopy() *ColorGroup {
	if in == nil {
		return nil
	}
	out := new(ColorGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	if in.BbRouters != nil {
		in, out := &in.BbRouters, &out.BbRouters
		*out = make([]BbRouterSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}
