# permissions for end users to view bgswitchercanaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgswitchercanary-viewer-role
rules:
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchercanaries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchercanaries/status
  verbs:
  - get
