# permissions for end users to edit bgswitchergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgswitchergroup-editor-role
rules:
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchergroups/status
  verbs:
  - get
