# permissions for end users to view bgswitchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgswitcher-viewer-role
rules:
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchers/status
  verbs:
  - get
