# permissions for end users to view bgswitchergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgswitchergroup-viewer-role
rules:
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchergroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seccamp.sabaniki.vsix.wide.ad.jp
  resources:
  - bgswitchergroups/status
  verbs:
  - get
