docker exec Blue-A vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:100:ace::1/128" > /dev/null
docker exec Blue-A vtysh -c "conf t" -c "router bgp 64600" -c " bgp router-id 10.64.60.1" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64502 64503 64601" -c " neighbor BB-BLUE peer-group" -c " neighbor BB-BLUE remote-as 64600" -c " neighbor EX-A peer-group" -c " neighbor EX-A remote-as 64501" -c " neighbor CONSUMERS peer-group" -c " neighbor blue-b interface peer-group BB-BLUE" -c " neighbor blue-c interface peer-group BB-BLUE" -c " neighbor ex-a interface peer-group EX-A" -c " neighbor pe-a interface peer-group CONSUMERS" -c " neighbor pe-a interface remote-as 64701" > /dev/null
docker exec Blue-A vtysh -c "conf t" -c "router bgp 64600" -c " address-family ipv6 unicast" -c "  network 2001:db8:6500::/48" -c "  network 2001:db8:6500:100:ace::1/128" -c "  neighbor BB-BLUE activate" -c "  neighbor BB-BLUE next-hop-self" -c "  neighbor BB-BLUE soft-reconfiguration inbound" -c "  neighbor EX-A activate" -c "  neighbor EX-A next-hop-self" -c "  neighbor EX-A soft-reconfiguration inbound" -c "  neighbor CONSUMERS activate" -c "  neighbor CONSUMERS next-hop-self" -c "  neighbor CONSUMERS soft-reconfiguration inbound" > /dev/null
docker exec Blue-B vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:100:cafe::1/128" > /dev/null
docker exec Blue-B vtysh -c "conf t" -c "router bgp 64600" -c " bgp router-id 10.64.60.2" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64502 64503 64601" -c " neighbor BB-BLUE peer-group" -c " neighbor BB-BLUE remote-as 64600" -c " neighbor EX-B peer-group" -c " neighbor EX-B remote-as 64502" -c " neighbor CONSUMERS peer-group" -c " neighbor blue-a interface peer-group BB-BLUE" -c " neighbor blue-c interface peer-group BB-BLUE" -c " neighbor ex-b interface peer-group EX-B" -c " neighbor pe-b interface peer-group CONSUMERS" -c " neighbor pe-b interface remote-as 64702" > /dev/null
docker exec Blue-B vtysh -c "conf t" -c "router bgp 64600" -c " address-family ipv6 unicast" -c "  network 2001:db8:6500::/48" -c "  network 2001:db8:6500:100:cafe::1/128" -c "  neighbor BB-BLUE activate" -c "  neighbor BB-BLUE next-hop-self" -c "  neighbor BB-BLUE soft-reconfiguration inbound" -c "  neighbor EX-B activate" -c "  neighbor EX-B next-hop-self" -c "  neighbor EX-B soft-reconfiguration inbound" -c "  neighbor CONSUMERS activate" -c "  neighbor CONSUMERS next-hop-self" -c "  neighbor CONSUMERS soft-reconfiguration inbound" > /dev/null
docker exec Blue-C vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:100:beef::1/128" > /dev/null
docker exec Blue-C vtysh -c "conf t" -c "router bgp 64600" -c " bgp router-id 10.64.60.3" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64502 64503 64601" -c " neighbor BB-BLUE peer-group" -c " neighbor BB-BLUE remote-as 64600" -c " neighbor EX-C peer-group" -c " neighbor EX-C remote-as 64503" -c " neighbor CONSUMERS peer-group" -c " neighbor blue-b interface peer-group BB-BLUE" -c " neighbor blue-a interface peer-group BB-BLUE" -c " neighbor ex-c interface peer-group EX-C" -c " neighbor pe-c interface peer-group CONSUMERS" -c " neighbor pe-c interface remote-as 64703" > /dev/null
docker exec Blue-C vtysh -c "conf t" -c "router bgp 64600" -c " address-family ipv6 unicast" -c "  network 2001:db8:6500::/48" -c "  network 2001:db8:6500:100:beef::1/128" -c "  neighbor BB-BLUE activate" -c "  neighbor BB-BLUE next-hop-self" -c "  neighbor BB-BLUE soft-reconfiguration inbound" -c "  neighbor EX-C activate" -c "  neighbor EX-C next-hop-self" -c "  neighbor EX-C soft-reconfiguration inbound" -c "  neighbor CONSUMERS activate" -c "  neighbor CONSUMERS next-hop-self" -c "  neighbor CONSUMERS soft-reconfiguration inbound" > /dev/null
docker exec Green-A vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:200:ace::1/128" > /dev/null
docker exec Green-A vtysh -c "conf t" -c "router bgp 64601" -c " bgp router-id 10.64.61.1" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64502 64503 64600" -c " neighbor BB-GREEN peer-group" -c " neighbor BB-GREEN remote-as 64601" -c " neighbor EX-A peer-group" -c " neighbor EX-A remote-as 64501" -c " neighbor CONSUMERS peer-group" -c " neighbor green-b interface peer-group BB-GREEN" -c " neighbor green-c interface peer-group BB-GREEN" -c " neighbor ex-a interface peer-group EX-A" -c " neighbor pe-a interface peer-group CONSUMERS" -c " neighbor pe-a interface remote-as 64701" > /dev/null
docker exec Green-A vtysh -c "conf t" -c "router bgp 64601" -c " address-family ipv6 unicast" -c "  network 2001:db8:6500::/48" -c "  network 2001:db8:6500:200:ace::1/128" -c "  neighbor BB-GREEN activate" -c "  neighbor BB-GREEN next-hop-self" -c "  neighbor BB-GREEN soft-reconfiguration inbound" -c "  neighbor EX-A activate" -c "  neighbor EX-A next-hop-self" -c "  neighbor EX-A soft-reconfiguration inbound" -c "  neighbor CONSUMERS activate" -c "  neighbor CONSUMERS next-hop-self" -c "  neighbor CONSUMERS soft-reconfiguration inbound" > /dev/null
docker exec Green-B vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:200:cafe::1/128" > /dev/null
docker exec Green-B vtysh -c "conf t" -c "router bgp 64601" -c " bgp router-id 10.64.61.2" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64502 64503 64600" -c " neighbor BB-GREEN peer-group" -c " neighbor BB-GREEN remote-as 64601" -c " neighbor EX-B peer-group" -c " neighbor EX-B remote-as 64502" -c " neighbor CONSUMERS peer-group" -c " neighbor green-a interface peer-group BB-GREEN" -c " neighbor green-c interface peer-group BB-GREEN" -c " neighbor ex-b interface peer-group EX-B" -c " neighbor pe-b interface peer-group CONSUMERS" -c " neighbor pe-b interface remote-as 64702" > /dev/null
docker exec Green-B vtysh -c "conf t" -c "router bgp 64601" -c " address-family ipv6 unicast" -c "  network 2001:db8:6500::/48" -c "  network 2001:db8:6500:200:cafe::1/128" -c "  neighbor BB-GREEN activate" -c "  neighbor BB-GREEN next-hop-self" -c "  neighbor BB-GREEN soft-reconfiguration inbound" -c "  neighbor EX-B activate" -c "  neighbor EX-B next-hop-self" -c "  neighbor EX-B soft-reconfiguration inbound" -c "  neighbor CONSUMERS activate" -c "  neighbor CONSUMERS next-hop-self" -c "  neighbor CONSUMERS soft-reconfiguration inbound" > /dev/null
docker exec Green-C vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:200:beef::1/128" > /dev/null
docker exec Green-C vtysh -c "conf t" -c "router bgp 64601" -c " bgp router-id 10.64.61.3" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64502 64503 64600" -c " neighbor BB-GREEN peer-group" -c " neighbor BB-GREEN remote-as 64601" -c " neighbor EX-C peer-group" -c " neighbor EX-C remote-as 64503" -c " neighbor CONSUMERS peer-group" -c " neighbor green-a interface peer-group BB-GREEN" -c " neighbor green-b interface peer-group BB-GREEN" -c " neighbor ex-c interface peer-group EX-C" -c " neighbor pe-c interface peer-group CONSUMERS" -c " neighbor pe-c interface remote-as 64703" > /dev/null
docker exec Green-C vtysh -c "conf t" -c "router bgp 64601" -c " address-family ipv6 unicast" -c "  network 2001:db8:6500::/48" -c "  network 2001:db8:6500:200:beef:1/128" -c "  neighbor BB-GREEN activate" -c "  neighbor BB-GREEN next-hop-self" -c "  neighbor BB-GREEN soft-reconfiguration inbound" -c "  neighbor EX-C activate" -c "  neighbor EX-C next-hop-self" -c "  neighbor EX-C soft-reconfiguration inbound" -c "  neighbor CONSUMERS activate" -c "  neighbor CONSUMERS next-hop-self" -c "  neighbor CONSUMERS soft-reconfiguration inbound" > /dev/null
docker exec EX-A vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:6451::1/128" > /dev/null
docker exec EX-A vtysh -c "conf t" -c "router bgp 64501" -c " bgp router-id 10.64.50.1" -c " no bgp ebgp-requires-policy" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " no bgp default ipv4-unicast" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64502 64503 64600 64601" -c " neighbor BB-BLUE peer-group" -c " neighbor BB-BLUE remote-as 64600" -c " neighbor BB-GREEN peer-group" -c " neighbor BB-GREEN remote-as 64601" -c " neighbor EX-AS peer-group" -c " neighbor EX-AS remote-as 65100" -c " neighbor EX-AS local-as 65000 no-prepend" -c " neighbor blue-a interface peer-group BB-BLUE" -c " neighbor green-a interface peer-group BB-GREEN" -c " neighbor blue-a route-map MED_LEVEL_BLUE out" -c " neighbor green-a interface MED_LEVEL_GREEN out" -c " neighbor ea-a interface peer-group EX-AS" > /dev/null
docker exec EX-A vtysh -c "conf t" -c "router bgp 64501" -c " address-family ipv6 unicast" -c "  redistribute connected" -c "  aggregate-address 2001:db8:6500::/48 summary-only" -c "  neighbor BB-BLUE activate" -c "  neighbor BB-BLUE next-hop-self" -c "  neighbor BB-BLUE soft-reconfiguration inbound" -c "  neighbor BB-GREEN activate" -c "  neighbor BB-GREEN next-hop-self" -c "  neighbor BB-GREEN soft-reconfiguration inbound" -c "  neighbor EX-AS activate" -c "  neighbor EX-AS next-hop-self" -c "  neighbor EX-AS soft-reconfiguration inbound" > /dev/null
docker exec EX-A vtysh -c "conf t" -c "route-map MED_LEVEL_BLUE permit 5" -c " set extcommunity bandwidth 1" > /dev/null
docker exec EX-A vtysh -c "conf t" -c "route-map MED_LEVEL_GREEN permit 10" -c " set extcommunity bandwidth 9" > /dev/null
docker exec EX-B vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:6452::1/128" > /dev/null
docker exec EX-B vtysh -c "conf t" -c "router bgp 64502" -c " bgp router-id 10.64.50.2" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64503 64600 64601" -c " neighbor BB-BLUE peer-group" -c " neighbor BB-BLUE remote-as 64600" -c " neighbor BB-GREEN peer-group" -c " neighbor BB-GREEN remote-as 64601" -c " neighbor EX-AS peer-group" -c " neighbor EX-AS remote-as 65200" -c " neighbor EX-AS local-as 65000 no-prepend" -c " neighbor blue-b interface peer-group BB-BLUE" -c " neighbor green-b interface peer-group BB-GREEN -c " neighbor blue-a route-map MED_LEVEL_BLUE out" -c " neighbor green-a interface MED_LEVEL_GREEN out" -c " neighbor ea-b interface peer-group EX-AS" > /dev/null
docker exec EX-B vtysh -c "conf t" -c "router bgp 64502" -c " address-family ipv6 unicast" -c "  redistribute connected" -c "  aggregate-address 2001:db8:6500::/48 summary-only" -c "  neighbor BB-BLUE activate" -c "  neighbor BB-BLUE next-hop-self" -c "  neighbor BB-BLUE soft-reconfiguration inbound" -c "  neighbor BB-GREEN activate" -c "  neighbor BB-GREEN next-hop-self" -c "  neighbor BB-GREEN soft-reconfiguration inbound" -c "  neighbor EX-AS activate" -c "  neighbor EX-AS next-hop-self" -c "  neighbor EX-AS soft-reconfiguration inbound" > /dev/null
docker exec EX-B vtysh -c "conf t" -c "route-map MED_LEVEL_BLUE permit 5" -c " set extcommunity bandwidth 1" > /dev/null
docker exec EX-B vtysh -c "conf t" -c "route-map MED_LEVEL_GREEN permit 10" -c " set extcommunity bandwidth 9" > /dev/null
docker exec EX-C vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6500:6453::1/128" > /dev/null
docker exec EX-C vtysh -c "conf t" -c "router bgp 64503" -c " bgp router-id 10.64.50.3" -c " no bgp ebgp-requires-policy" -c " no bgp default ipv4-unicast" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " bgp confederation identifier 65000" -c " bgp confederation peers 64501 64502 64600 64601" -c " neighbor BB-BLUE peer-group" -c " neighbor BB-BLUE remote-as 64600" -c " neighbor BB-GREEN peer-group" -c " neighbor BB-GREEN remote-as 64601" -c " neighbor EX-AS peer-group" -c " neighbor EX-AS remote-as 65300" -c " neighbor EX-AS local-as 65000 no-prepend" -c " neighbor blue-c interface peer-group BB-BLUE" -c " neighbor green-c interface peer-group BB-GREEN" -c " neighbor blue-a route-map MED_LEVEL_BLUE out" -c " neighbor green-a interface MED_LEVEL_GREEN out" -c " neighbor ea-c interface peer-group EX-AS" > /dev/null
docker exec EX-C vtysh -c "conf t" -c "router bgp 64503" -c " address-family ipv6 unicast" -c "  redistribute connected" -c "  aggregate-address 2001:db8:6500::/48 summary-only" -c "  neighbor BB-BLUE activate" -c "  neighbor BB-BLUE next-hop-self" -c "  neighbor BB-BLUE soft-reconfiguration inbound" -c "  neighbor BB-GREEN activate" -c "  neighbor BB-GREEN next-hop-self" -c "  neighbor BB-GREEN soft-reconfiguration inbound" -c "  neighbor EX-AS activate" -c "  neighbor EX-AS next-hop-self" -c "  neighbor EX-AS soft-reconfiguration inbound" > /dev/null
docker exec EX-C vtysh -c "conf t" -c "route-map MED_LEVEL_BLUE permit 5" -c " set extcommunity bandwidth 1" > /dev/null
docker exec EX-C vtysh -c "conf t" -c "route-map MED_LEVEL_GREEN permit 10" -c " set extcommunity bandwidth 9" > /dev/null
docker exec PE-A vtysh -c "conf t" -c "interface cm-a" -c " ipv6 address 2001:db8:6500:6471::1/64" > /dev/null
docker exec PE-A vtysh -c "conf t" -c "router bgp 64701" -c " bgp router-id 10.64.70.1" -c " no bgp ebgp-requires-policy" -c " no bgp ebgp-requires-policy" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " no bgp default ipv4-unicast" -c " neighbor BB peer-group" -c " neighbor BB remote-as 65000" -c " neighbor blue-a interface peer-group BB" -c " neighbor green-a interface peer-group BB" -c " neighbor blue-a route-map MED_LEVEL_BLUE out" -c " neighbor green-a interface MED_LEVEL_GREEN out" > /dev/null
docker exec PE-A vtysh -c "conf t" -c "router bgp 64701" -c " address-family ipv6 unicast" -c "  redistribute connected" -c "  neighbor BB activate" -c "  neighbor BB soft-reconfiguration inbound" > /dev/null
docker exec PE-A vtysh -c "conf t" -c "route-map MED_LEVEL_BLUE permit 5" -c " set extcommunity bandwidth 1" > /dev/null
docker exec PE-A vtysh -c "conf t" -c "route-map MED_LEVEL_GREEN permit 10" -c " set extcommunity bandwidth 9" > /dev/null
docker exec PE-B vtysh -c "conf t" -c "interface cm-b" -c " ipv6 address 2001:db8:6500:6472::1/64" > /dev/null
docker exec PE-B vtysh -c "conf t" -c "router bgp 64702" -c " bgp router-id 10.64.70.2" -c " no bgp ebgp-requires-policy" -c " no bgp ebgp-requires-policy" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " no bgp default ipv4-unicast" -c " neighbor BB peer-group" -c " neighbor BB remote-as 65000" -c " neighbor blue-b interface peer-group BB" -c " neighbor green-b interface peer-group BB" -c " neighbor blue-a route-map MED_LEVEL_BLUE out" -c " neighbor green-a interface MED_LEVEL_GREEN out" > /dev/null
docker exec PE-B vtysh -c "conf t" -c "router bgp 64702" -c " address-family ipv6 unicast" -c "  redistribute connected" -c "  neighbor BB activate" -c "  neighbor BB soft-reconfiguration inbound" > /dev/null
docker exec PE-B vtysh -c "conf t" -c "route-map MED_LEVEL_BLUE permit 5" -c " set extcommunity bandwidth 1" > /dev/null
docker exec PE-B vtysh -c "conf t" -c "route-map MED_LEVEL_GREEN permit 10" -c " set extcommunity bandwidth 9" > /dev/null
docker exec PE-C vtysh -c "conf t" -c "interface cm-c" -c " ipv6 address 2001:db8:6500:6473::1/64" > /dev/null
docker exec PE-C vtysh -c "conf t" -c "router bgp 64703" -c " bgp router-id 10.64.70.3" -c " no bgp ebgp-requires-policy" -c " no bgp ebgp-requires-policy" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " no bgp default ipv4-unicast" -c " neighbor BB peer-group" -c " neighbor BB remote-as 65000" -c " neighbor blue-c interface peer-group BB" -c " neighbor green-c interface peer-group BB" -c " neighbor blue-a route-map MED_LEVEL_BLUE out" -c " neighbor green-a interface MED_LEVEL_GREEN out" > /dev/null
docker exec PE-C vtysh -c "conf t" -c "router bgp 64703" -c " address-family ipv6 unicast" -c "  redistribute connected" -c "  neighbor BB activate" -c "  neighbor BB soft-reconfiguration inbound" > /dev/null
docker exec PE-C vtysh -c "conf t" -c "route-map MED_LEVEL_BLUE permit 5" -c " set extcommunity bandwidth 1" > /dev/null
docker exec PE-C vtysh -c "conf t" -c "route-map MED_LEVEL_GREEN permit 10" -c " set extcommunity bandwidth 9" > /dev/null
docker exec CM-A vtysh -c "conf t" -c "interface pe-a" -c " ipv6 address 2001:db8:6500:6471::2/64" > /dev/null
docker exec CM-A vtysh -c "conf t" -c "ip route ::/0 2001:db8:6500:6471::1" > /dev/null
docker exec CM-B vtysh -c "conf t" -c "interface pe-b" -c " ipv6 address 2001:db8:6500:6472::2/64" > /dev/null
docker exec CM-B vtysh -c "conf t" -c "ip route ::/0 2001:db8:6500:6472::1" > /dev/null
docker exec CM-C vtysh -c "conf t" -c "interface pe-c" -c " ipv6 address 2001:db8:6500:6473::2/64" > /dev/null
docker exec CM-C vtysh -c "conf t" -c "ip route ::/0 2001:db8:6500:6473::1" > /dev/null
docker exec EA-A vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6510::1/128" > /dev/null
docker exec EA-A vtysh -c "conf t" -c "router bgp 65100" -c " bgp router-id 10.65.10.0" -c " no bgp ebgp-requires-policy" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " no bgp default ipv4-unicast" -c " neighbor TESTBED peer-group" -c " neighbor TESTBED remote-as 65000" -c " neighbor ex-a interface peer-group TESTBED" > /dev/null
docker exec EA-A vtysh -c "conf t" -c "router bgp 65100" -c " address-family ipv6 unicast" -c "  network  2001:db8:6510::/48" -c "  neighbor TESTBED activate" -c "  neighbor TESTBED soft-reconfiguration inbound" > /dev/null
docker exec EA-B vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6520::1/128" > /dev/null
docker exec EA-B vtysh -c "conf t" -c "router bgp 65200" -c " bgp router-id 10.65.20.0" -c " no bgp ebgp-requires-policy" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " no bgp default ipv4-unicast" -c " neighbor TESTBED peer-group" -c " neighbor TESTBED remote-as 65000" -c " neighbor ex-b interface peer-group TESTBED" > /dev/null
docker exec EA-B vtysh -c "conf t" -c "router bgp 65200" -c " address-family ipv6 unicast" -c "  network 2001:db8:6520::/48" -c "  neighbor TESTBED activate" -c "  neighbor TESTBED soft-reconfiguration inbound" > /dev/null
docker exec EA-C vtysh -c "conf t" -c "interface lo" -c " ipv6 address 2001:db8:6530::1/128" > /dev/null
docker exec EA-C vtysh -c "conf t" -c "router bgp 65300" -c " bgp router-id 10.65.30.0" -c " no bgp ebgp-requires-policy" -c " no bgp suppress-duplicates" -c " no bgp network import-check" -c " no bgp default ipv4-unicast" -c " neighbor TESTBED peer-group" -c " neighbor TESTBED remote-as 65000" -c " neighbor ex-c interface peer-group TESTBED" > /dev/null
docker exec EA-C vtysh -c "conf t" -c "router bgp 65300" -c " address-family ipv6 unicast" -c "  network 2001:db8:6530::/48" -c "  neighbor TESTBED activate" -c "  neighbor TESTBED soft-reconfiguration inbound" > /dev/null
