version: '3'
services:
  Blue-A:
    restart: always
    image: blue-a
    environment:
      - NAME=blue-a
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns

  # Blue-B:
  #   restart: always
  #   image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
  #   environment:
  #     - NAME="Blue-B"
  #   privileged: true
  #   user: "0:0"
  #   network_mode: host
  #   volumes:
  #     - /home/sabaniki/.kube/config:/root/.kube/config
  #     - /var/run:/var/run
  #     - /proc:/proc
  #     - /etc/netns:/etc/netns

  # Blue-C:
  #   restart: always
  #   image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
  #   environment:
  #     - NAME="Blue-C"
  #   privileged: true
  #   user: "0:0"
  #   network_mode: host
  #   volumes:
  #     - /home/sabaniki/.kube/config:/root/.kube/config
  #     - /var/run:/var/run
  #     - /proc:/proc
  #     - /etc/netns:/etc/netns

  Green-A:
    restart: always
    image: green-a
    environment:
      - NAME=green-a
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns

  # Green-B:
  #   restart: always
  #   image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
  #   environment:
  #     - NAME="Green-B"
  #   privileged: true
  #   user: "0:0"
  #   network_mode: host
  #   volumes:
  #     - /home/sabaniki/.kube/config:/root/.kube/config
  #     - /var/run:/var/run
  #     - /proc:/proc
  #     - /etc/netns:/etc/netns

  # Green-C:
  #   restart: always
  #   image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
  #   environment:
  #     - NAME="Green-C"
  #   privileged: true
  #   user: "0:0"
  #   network_mode: host
  #   volumes:
  #     - /home/sabaniki/.kube/config:/root/.kube/config
  #     - /var/run:/var/run
  #     - /proc:/proc
  #     - /etc/netns:/etc/netns

networks:
  default:
    name: kind
    external: true
