version: '3'
services:
  EX-A:
    restart: always
    image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
    environment:
      - NAME=ex-a
      - MADDR=8080
      - PADDR=9090
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns

  EX-B:
    restart: always
    image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
    environment:
      - NAME=ex-b
      - MADDR=8081
      - PADDR=9091
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns

  EX-C:
    restart: always
    image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
    environment:
      - NAME=ex-c
      - MADDR=8082
      - PADDR=9092
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns

  PE-A:
    restart: always
    image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
    environment:
      - NAME=pe-a
      - MADDR=8083
      - PADDR=9093
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns

  PE-B:
    restart: always
    image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
    environment:
      - NAME=pe-b
      - MADDR=8084
      - PADDR=9094
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns

  PE-C:
    restart: always
    image: ghcr.io/sabaniki/seccamp/bg-switcherlet:latest
    environment:
      - NAME=pe-c
      - MADDR=8085
      - PADDR=9095
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/sabaniki/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /proc:/proc
      - /etc/netns:/etc/netns